[platformio]
default_envs = esp32
src_dir = firmware/src
include_dir = firmware/include

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
framework = arduino
extra_scripts = post:tools/patch_arduino_wifi_ampdu.py
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions.csv
build_flags =
    -D CORE_DEBUG_LEVEL=0

[env:esp32]
board = esp32dev
build_flags =
    ${env.build_flags}
    -D HWTEST_PROFILE=\"esp32\"

[env:esp32-c3]
board = esp32-c3-devkitm-1
build_flags =
    ${env.build_flags}
    -D HWTEST_PROFILE=\"esp32-c3\"
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1    

[env:esp32-s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
build_flags =
    ${env.build_flags}
    -D HWTEST_PROFILE=\"esp32-s3\"

[env:esp32-s3-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    ${env.build_flags}
    -D HWTEST_PROFILE=\"esp32-s3-n16r8\"
    -D BOARD_HAS_PSRAM
