# Local Wi-Fi credentials for the ESP32 Board Test.
# This example file may be committed to Git.
# For an actual test, copy this file to "secrets.ini"
# and enter the real credentials there.

WIFI_SSID=MyWiFi
WIFI_PASSWORD=MyPassword
