[platformio]
default_envs = esp32
src_dir = src

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
framework = arduino
extra_scripts = pre:../tools/patch_arduino_wifi_ampdu.py
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -D CORE_DEBUG_LEVEL=0

[env:esp32]
board = esp32dev

[env:esp32-c3]
board = esp32-c3-devkitm-1

[env:esp32-s3]
board = esp32-s3-devkitc-1

[env:esp32-s3-n16r8]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
    ${env.build_flags}
    -D BOARD_HAS_PSRAM
